# project information
site_name: InvestSuite API documentation
site_url: https://api.investsuite.com/docs
site_author: InvestSuite
site_description: >-
  The InvestSuite API is the one-stop shop for integrations with InvestSuite's
  range of invest-tech solutions. These pages provide technical documentation to
  assist developers working with our APIs.

# docs repository
repo_name: View/Edit on GitHub
repo_url: https://github.com/investsuite/investsuite-api-docs
edit_uri: /investsuite/investsuite-api-docs/blob/master/docs

# copyright
copyright: Copyright &copy; 2021 InvestSuite

# mkdocs config
theme:
  name: material
  custom_dir: overrides

  # don't include mkdocs javascript
  include_search_page: false
  search_index_only: true

  palette:
    scheme: investsuite
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  icon:
    repo: fontawesome/solid/book
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

# social links
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.investsuite.com/
    - icon: fontawesome/solid/envelope
      link: mailto:hello@investsuite.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/investsuite
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/investsuite
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/investsuite

# add custom css
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - meta
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - footnotes

plugins:
  - search:
      lang: en
  - git-info

nav:
  - Home: 
    - Introduction: index.md
    - First steps: first_steps.md
    - Creating and managing users: users.md
  - Advanced Topics:
    - Next steps: advanced_topics/next_steps.md
    # - Data formats: advanced_topics/data_formats.md
    - Handling collection responses: advanced_topics/collections.md
    - A closer look at API errors : advanced_topics/errors.md
    # - Debugging tips and tricks: advanced_topics/debugging.md
    # - Rate limiting: advanced_topics/rate_limiting.md
    # - Idempotency: advanced_topics/idempotency.md
    - Embedding: advanced_topics/embedding.md
    # - Asynchronous operations: advanced_topics/async.md
  - Changelog: changelog.md
  - About: about.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/timeago.js/4.0.2/timeago.min.js