name: publish docs
on:
  push:
    branches:
      - master

jobs:
  docs:
    name: publish docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up Python runtime
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: publish docs
        run: |
          mkdocs gh-deploy